near/create-near-app

- blank_react_project/src/index.js
Very simple deprecation replacement. I'm new to NEAR Protocol's codebase, but this seems like a quick fix.
> replace deprecated call to loadContract

- package.json
I have this [in another PR](https://github.com/nearprotocol/create-near-app/pull/138) that's await approval, but I think it's very important to have the `engines` key specified for the node versions. Peter already ran into this as a problem. I want to fast track this change.
Also, while I was in there I improved some of the keywords. `assembly` for instance, is not a good keyword for us.
> package.json engine for node >= 12, better keywords

- .travis.yml
This adds multiple operating systems to the list of those checked by Travis.
Also has conditionals for Windows and non-Windows in order to install npm, which installs yarn.
And add `cache: cargo` as recommended here:
https://docs.travis-ci.com/user/languages/rust/
> Travis, check multiple OSes, conditions installing npm

- .travis.yml
As we mentioned internally, having Travis check the Rust nightly every time is overkill. We have discussed the possibility of having this check in a nightly CI.
At this time, the decision has been to remove nightly as we're using Rust `stable` anyway.
This will cut the number of CI tests in half.
> travis: remove rust nightly check, check stable only

- .travis.yml
- blank_project/src/config.js
- blank_react_project/src/config.js
- blank_rust_project/src/config.js
- blank_rust_react_project/src/config.js
<a href="https://gitpod.io/#https://github.com/nearprotocol/create-near-app/pull/235"><img src="https://gitpod.io/api/apps/github/pbs/github.com/nearprotocol/create-near-app.git/ff61990774b12042eaf668261cf265d908494d1a.svg" /></a>
> Trying to add and use ci-betanet config

- blank_project/package.json
- blank_react_project/package.json
- blank_rust_project/package.json
- blank_rust_react_project/package.json
- package.json
Partially addresses https://github.com/near/devx/issues/155
I've added a `license` line to the generated `package.json` files, as they did not have this line previously. However, I did not also add `LICENSE` or `LICENSE-APACHE` files to those repositories.
Do we want to generate projects with the same dual license that we use as our NEAR standard? Or should this change only be for the root `package.json`?
> chore: add dual license to all package.json

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- blank_project/README.md
- blank_project/src/index.html
- blank_project/src/main.js
- blank_react_project/README.md
- blank_react_project/src/App.css
- blank_react_project/src/App.js
- blank_react_project/src/__snapshots__/App.test.js.snap
- blank_react_project/src/index.js
- blank_rust_project/README.md
- blank_rust_project/src/index.html
- blank_rust_project/src/main.js
- blank_rust_react_project/README.md
- blank_rust_react_project/src/App.css
- blank_rust_react_project/src/App.js
- blank_rust_react_project/src/__snapshots__/App.test.js.snap
- blank_rust_react_project/src/index.js
- contract/rust/Cargo.toml
- package.json
fixes near/devx#217
Using [ripgrep]:
* `for f in $(rg -l nearprotocol\.com); do sed -i '' 's/nearprotocol.com/near.org/' $f; done`
* `for f in $(rg -l DevNet); do sed -i '' 's/DevNet/testnet/' $f; done`
* `for f in $(rg -l wallet\.near\.org); do sed -i '' 's/wallet.near.org/wallet.testnet.near.org/' $f; done`
[ripgrep]: https://github.com/BurntSushi/ripgrep
> chore: replace nearprotocol.com with near.org

- blank_project/asconfig.js
- blank_project/package.json
- blank_react_project/asconfig.js
- blank_react_project/package.json
This was removed in [v10.0.0](https://github.com/AssemblyScript/assemblyscript/releases/tag/v0.10.0)
We have been using this version since at least 1dd59324cfc779becf9e5ee1127925ad8b89adfc
> fix: rm obsolete --validate flag from asconfig

- blank_project/README.md
- blank_react_project/README.md
- blank_rust_project/README.md
- blank_rust_react_project/README.md
Fixing an issue Anais saw that is mentioned here:
https://github.com/zkat/npx/issues/209
> add troubleshooting section to frontend readmes, include npx space issue

- common/frontend/config.js
- templates/react/src/App.js
- templates/vanilla/src/main.js
this was missed in #372
in the notification that links people to NEAR Explorer, we need to link
to the version of explorer for their selected network. This way, if
someone runs their new app on betanet, the links in the notification
don't lead to 404 pages.
> feat: use current networkId in notification

- .gitignore
- .npmignore
- .travis.yml
- README.md
- index.js
- package.json
- templates/react/assembly
- templates/react/package.json
- templates/react/src/assets
- templates/react/src/config.js
- templates/react/src/global.css
- templates/react/src/utils.js
- templates/vanilla/assembly
- templates/vanilla/package.json
- templates/vanilla/src/assets
- templates/vanilla/src/config.js
- templates/vanilla/src/global.css
- templates/vanilla/src/utils.js
Previously, in order to make changes to one of the templates in
create-near-app, the development process looked something like:
1. use create-near-app to generate a new app
2. fix bugs or make improvements in the new app
3. backport the changes to create-near-app proper
This is error-prone and slow, and makes it hard for people new to
create-near-app to submit improvements.
Instead, this change makes it possible to switch right into a template
directory and start working:
1. `cd templates/vanilla` or `cd templates/react`
2. run `yarn`, `yarn test`, `yarn dev`, or whatever. Make changes.
Now your changes are immediately reflected to the correct file in
the `create-near-app` repo with no backporting. And when you actually
use `create-near-app` to create a new project, the symlinks and …
> feat: rapid development for create-near-app itself

- README.md
README.md clearly describes how to use `npx`, but doesn't provide an example with Yarn.
This PR adds a note about Yarn usage in Getting Started.
> README.md: adding a note about `yarn create`

- common/frontend/utils.js
- templates/vanilla/src/main.js
I recommend reviewing the code [with indentation changes hidden](https://github.com/near/create-near-app/pull/398/files?diff=unified&w=1)
Fixes #391 by moving button disabling to vanilla/src/main.js, as this logic interferes with React's state management and breaks the React app
Fixes #397 (also fixes #70) by adding error handling to the setGreeting and moving form reenabling to the `finally` clause of the promise resolution
> fix: catch error on setGreeting

- common/frontend/utils.js
This parameter is no longer used by NEAR Wallet: https://github.com/near/near-wallet/pull/725
This also adds more info to the comment to hopefully guide people toward a more precise understanding of what "signing in" means
> fix(requestSignIn): rm obsolete app name parameter

- common/contracts/assemblyscript/main.ts
- common/contracts/rust/Cargo.lock
- common/contracts/rust/Cargo.toml
- common/contracts/rust/build.js
- common/contracts/rust/src/lib.rs
- templates/react/packagejsons/rust/package.json
- templates/vanilla/packagejsons/rust/package.json
A redo of https://github.com/near/create-near-app/pull/101, which had
good stuff but targeted a very different version of create-near-app
Things that might not be super obvious from just reading the new
comments:
* rename rust project from "status-message", which had nothing to do
with this project, to "greeter"
* remove superfluous references to contract name (`--package` stuff)
* move `env::log` to `set_greeting`, making it easier to find in NEAR Explorer
* Simplify `match` expression
> refactor(contracts): simplify & add comments

- .travis.yml
- README.md
- commitlint.config.js
- package.json
- yarn.lock
This adds some tooling to make sure we use [Conventional Commits] and
use them to their fullest
* use [commitlint] & [husky] to check commit messages & reject any that
don't fit the Conventional Commits format
* use [standard-version] to automatically update CHANGELOG, set new
version number, and publish a release to NPM
[Conventional Commits]: https://www.conventionalcommits.org/
[commitlint]: https://commitlint.js.org/
[husky]: https://www.npmjs.com/package/husky
[standard-version]: https://github.com/conventional-changelog/standard-version
> build: add & enforce Conventional Commits

- .travis.yml
- test/test-new-project.js
Partially addresses #416 
* remove ci-betanet tests (discussed this with @vgrichina first; given that we include these more to verify betanet than to test the project-under-test, and given that we already include betanet tests for lots of repos with faster-running tests, it doesn't seem necessary to include them here)
* run specific contract/frontend combos in separate jobs
* use NEAR_ENV instead of NODE_ENV
> chore: streamline & speed up CI builds

- common/contracts/assemblyscript/README.md
- common/contracts/rust/README.md
- templates/react/packagejsons/assemblyscript/package.json
- templates/react/packagejsons/rust/package.json
- templates/react/src/main.test.js
- templates/react/src/wallet/login/index.html
- templates/vanilla/packagejsons/assemblyscript/package.json
- templates/vanilla/packagejsons/rust/package.json
- templates/vanilla/src/main.test.js
- templates/vanilla/src/wallet/login/index.html
We're now using
https://www.npmjs.com/package/near-cli
and have a deprecation warning at the top of:
https://www.npmjs.com/package/near-shell
Also the Github has been renamed to:
https://github.com/near/near-cli
> Use near-cli instead of near-shell

- .gitignore
- index.js
- yarn.lock
- if the user mistypes an option, for example `create-near-app --frrontend react myapp`, the option was ignored and the app created anyway with the default options (vanilla).
By adding `.strict()`, yargs emits an error
fix: work even if yarn is not installed, fixes #409
> (fix): add .strict() to yargs to catch mistyped options

- common/contracts/rust/Cargo.toml
Fixes #498 
By default, Rust has overflow checks enabled for debug builds, but disabled in optimized release builds. This adds the checks for production builds as well.
> feat: add overflow-checks to Rust release profile

- templates/.npmignore
- templates/angular/near.gitignore
- templates/react/near.gitignore
- templates/vanilla/near.gitignore
- templates/vue/near.gitignore
We do not want lockfiles to be included in the artifact pushed to npmjs.com, as we do not want to assume ahead of time if a newly-created project is using npm or yarn
Likewise, we do not want to ignore package-lock.json, as a project's creator may prefer to use npm instead of yarn
> build: npmignore lockfiles, don't gitignore

- templates/angular/packagejsons/rust/package.json
- templates/vue/packagejsons/rust/package.json
- test/test-new-project.js
I noticed that sometimes the tests could pass, even though generating a
particular contract+frontend combo failed. This could happen when the
frontend had dependencies covered by the root `package.json`, but not
actually included its own `package.json`
Why did this happen? Because we were creating the test project inside
the root folder, so when the test project tried to look up a given
dependency, it was able to find it in the root project's node_modules
folder.
We need to make sure we test in a realistic environment, where the
project cannot depend on the root folder's node_modules
> build: test in diff folder, avoid false positives

- templates/angular/package.json
- templates/react/package.json
- templates/vanilla/package.json
- templates/vue/package.json
Node 15 (or is it because of NPM 7?) updates `package.json` and `package-lock.json` every time you run `npm install`. Since the `contract/compile` script runs `npm install`, this means that running `yarn dev` updates these files. And since `yarn dev` also watches these files for changes and re-runs if it spots any, Node 15 causes an infinite loop.
This instructs nodemon to ignore the `package*.json` files.
> fix: prevent infinite 'yarn dev' loop on node15

- common/contracts/assemblyscript/package.json
Works around https://github.com/near/near-sdk-as/issues/337
create-near-app is currently broken with all 2.x.x versions of near-sdk-as. Using v1.0.0 works, so let's roll back for now.
Also, this uses a specific version, since contracts can be even more sensitive to version changes than frontend apps, and we already started being more careful with our frontend package.json versioning: https://github.com/near/create-near-app/pull/532
> fix(assemblyscript): roll back to v1.0.0

- index.js
- package.json
- rustup-setup.js
- utils/rust-setup.js
- yarn.lock
Tested on Linux (Arch + Bash/ZSH)
Latest Mac OS (ZSH)
Windows 10 (Power Shell)
It will be great to run it on your PC. Don't forget to clear `.bashrc`, `.zshenv`, etc., and make sure that cargo is not in the `PATH` before the test.
Example:
```
node ../create-near-app/index.js coolApp --contract=rust
...[some boilerplate here]...
Checking if rustup is installed...
rustup is not installed
In order to work with rust smart contracts we recommend you install rustup, the Rust toolchain installer. We can run the following command to do it for you:
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
Continue with installation (Y/n)?: y
Installing rustup...
...[some boilerplate from Rust]...
Checking installed Rust targets..
x86_64-unknown-linux-gnu
wasm32-unknown-unknown …
```
> rustup and wasm32-unknown-unknown auto setup

- templates/react/near.gitignore
the `.cache` and `dist` folders aren't being ignored by default.
Also, for Rust contracts the `target` directory wasn't being ignored, but looking at the code it seems to be doing it correctly so it might just not be released? If not, happy to fix that, but it wasn't intuitive for me how to run from source (my JS is rusty sorry)
> fix(generated): fix react git ignore

- templates/vanilla/src/index.html
In #389 main.js and main.ts files were renamed to index.js and index.ts .
This can be confusing to newcomers who read the instructions on the index.html .
> Update references to main files in index.html

- .github/workflows/test-matrix.yml
- index.js
- templates/angular/package.json
- templates/react/package.json
- templates/vanilla/package.json
- templates/vue/package.json
We need to release a new version of `create-near-app` since dev-deploy is not working because of outdated `near-cli`. These are additional changes that we want to have in this release:
- `near-api-js` updated to v0.43.1
- deprecation message added for `angular` front-end (it was planned a long time ago, the project is not in use and hard to maintain)
> Updated to naj 0.43.1, angular frontend deprecated

- near.gitignore
- templates/angular/near.gitignore
- templates/react/near.gitignore
- templates/vanilla/near.gitignore
- templates/vue/near.gitignore
ignore all directories called node_modules. 
Without this change nested `contract/node_modules` will not be ignored as shown below
> fix(near.gitignore): ignore nested node_modules

- templates/contracts/rust/Cargo.toml
- test/__snapshots__/make.test.ts.snap
It's inefficient, should not be defaulting to this as it has no benefit and just disables LTO
> fix: remove rlib from Rust template crate type

- .github/workflows/test-e2e.yml
- package.json
- src/make.ts
- src/messages.ts
- src/package-json.ts
- src/tracking.ts
- templates/shared/README.md
- test/__snapshots__/make.test.ts.snap
- test/__snapshots__/user-input.test.ts.snap
unclear to me why this isn't hooked into install. This was a footgun I ran into, devs shouldn't have to know about this command.
Tests were already broken, didn't extensively test this
> fix: remove need for specific deps-install command, use install

- .github/workflows/test-e2e.yml
- README.md
Added a similar warning to create-react-app: https://create-react-app.dev/docs/getting-started/
> fix: readme - warn about global installation

- templates/integration-tests/js-tests/src/main.ava.ts
- test/__snapshots__/make.test.ts.snap
Before this change, we were not stopping near-sandbox processes in case the test failed. With time it leads to high memory, CPU, and battery usage.
afterEach.always(...) solves the problem.
> always kill sandbox process

- templates/contracts/rust/README.md
Rust template contract field name is [`message`](https://github.com/luuuu-learning/create-near-app/blob/master/templates/contracts/rust/src/lib.rs#L19), but in readme the [`set_greeting`](https://github.com/luuuu-learning/create-near-app/blob/master/templates/contracts/rust/README.md?plain=1#L81) instruction is using `greeting` as field name, which will get missing field error if we call it.
```
ServerTransactionError: {"index":0,"kind":{"ExecutionError":"Smart contract panicked: panicked at 'Failed to deserialize input from JSON.: Error(\"missing field `message`\", line: 1, column: 20)', src/lib.rs:30:1"}}
```
> fix: rust template deploy instruction is broken

- templates/shared/rust-toolchain.toml
As contracts compiled with Rust 1.70 are not working currently this commit ensures that users who use rustup aren't experiencing errors. Resolves #2009
Note that the e2e tests are failing for me locally both with and without this commit. I'd likely to see if they succeed in the CI before investigating further.
> fix: force Rust 1.69 with rust-toolchain.toml

- src/package-json.ts
- test/__snapshots__/make.test.ts.snap
The integration tests depend on a built artifact, so they'll fail unless the `build:contract` command is ran manually before running integration tests.
It's also error-prone as users might not realize that they have to rebuild manually before running integration tests, and they might get confused.
Incidentally this change also fixes the e2e tests that were failing in master locally on a fresh checkout of the repository.
Branched out from https://github.com/near/create-near-app/pull/2013, otherwise tests are failing.
> Build contract before integration tests

- templates/contracts/ts/package.json
The `test` script in package.json currently requires the user to manually build the contract in prior to running the tests.
Ideally the flow would be the same as the `test.sh` script for the rust smart contract where the test script builds the contract prior execution.
> refactor: change the npm test script to build the ts contract

- templates/contracts/ts/package.json
yarn does not have `i` so it is better to use the generic `"install"`
> fix: use install instead of i

- templates/contracts/ts/package.json
Before on `pnpm run test` for the contract template with TS:
```
Error {
message: 'Could not find \'--\' relative to any package.json file or your current working directory (/home/matt/Documents/hello-near-ts/sandbox-ts)',
}
```
Now it works fine.
> fix(contracts/ts): remove erroneous `--` in test script

- README.md
The following links were broken and fixed:
* Prerequisites https://docs.near.org/build/smart-contracts/quickstart#prerequisites
* Smart Contract Quickstart https://docs.near.org/build/smart-contracts/quickstart
* Web App Quickstart https://docs.near.org/build/web3-apps/quickstart
> Fixing broken links in create-near-app README File

- .github/workflows/test-contract-rs.yml
- .github/workflows/test-matrix.yml
Maintenance update to setup-node@v4 to align with the current best practices; nothing else modified. Refer to [v4.0.0 release notes](https://github.com/actions/setup-node/releases/tag/v4.0.0) for details.
> chore(ci): upgrade setup-node to v4
